package aplicacao;

public enum StatusSaque {
    SUCESSO,
    REQUISICAO_INVALIDA,
    CONTA_NAO_ENCONTRADA,
    SALDO_CONTA_INSUFICIENTE,
    DINHEIRO_CAIXA_INSUFICIENTE,
    SALDO_CONTA_E_DINHEIRO_CAIXA_INSUFICIENTES,
    COMPOSICAO_EXATA_INDISPONIVEL
}
